/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __V3270TRACE_MARSHAL_H__
#define __V3270TRACE_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* BOOLEAN:POINTER,POINTER (src/trace/marshal:1) */
extern
void v3270trace_BOOLEAN__POINTER_POINTER (GClosure     *closure,
                                          GValue       *return_value,
                                          guint         n_param_values,
                                          const GValue *param_values,
                                          gpointer      invocation_hint,
                                          gpointer      marshal_data);


G_END_DECLS

#endif /* __V3270TRACE_MARSHAL_H__ */
