/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __V3270_MARSHAL_H__
#define __V3270_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:VOID (src/terminal/marshal:1) */
#define v3270_VOID__VOID	g_cclosure_marshal_VOID__VOID

/* VOID:VOID,ENUM,BOOLEAN,POINTER (src/terminal/marshal:2) */
extern
void v3270_VOID__VOID_ENUM_BOOLEAN_POINTER (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);

/* VOID:VOID,ENUM (src/terminal/marshal:3) */
extern
void v3270_VOID__VOID_ENUM (GClosure     *closure,
                            GValue       *return_value,
                            guint         n_param_values,
                            const GValue *param_values,
                            gpointer      invocation_hint,
                            gpointer      marshal_data);

/* VOID:VOID,POINTER (src/terminal/marshal:4) */
extern
void v3270_VOID__VOID_POINTER (GClosure     *closure,
                               GValue       *return_value,
                               guint         n_param_values,
                               const GValue *param_values,
                               gpointer      invocation_hint,
                               gpointer      marshal_data);

/* VOID:POINTER (src/terminal/marshal:5) */
#define v3270_VOID__POINTER	g_cclosure_marshal_VOID__POINTER

/* VOID:VOID,POINTER,POINTER (src/terminal/marshal:6) */
extern
void v3270_VOID__VOID_POINTER_POINTER (GClosure     *closure,
                                       GValue       *return_value,
                                       guint         n_param_values,
                                       const GValue *param_values,
                                       gpointer      invocation_hint,
                                       gpointer      marshal_data);

/* VOID:VOID,UINT,POINTER (src/terminal/marshal:7) */
extern
void v3270_VOID__VOID_UINT_POINTER (GClosure     *closure,
                                    GValue       *return_value,
                                    guint         n_param_values,
                                    const GValue *param_values,
                                    gpointer      invocation_hint,
                                    gpointer      marshal_data);

/* BOOLEAN:UINT,ENUM (src/terminal/marshal:8) */
extern
void v3270_BOOLEAN__UINT_ENUM (GClosure     *closure,
                               GValue       *return_value,
                               guint         n_param_values,
                               const GValue *param_values,
                               gpointer      invocation_hint,
                               gpointer      marshal_data);

/* VOID:VOID,BOOLEAN (src/terminal/marshal:9) */
extern
void v3270_VOID__VOID_BOOLEAN (GClosure     *closure,
                               GValue       *return_value,
                               guint         n_param_values,
                               const GValue *param_values,
                               gpointer      invocation_hint,
                               gpointer      marshal_data);

/* BOOLEAN:VOID,BOOLEAN,BOOLEAN,POINTER (src/terminal/marshal:10) */
extern
void v3270_BOOLEAN__VOID_BOOLEAN_BOOLEAN_POINTER (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* VOID:VOID,UINT,UINT (src/terminal/marshal:11) */
extern
void v3270_VOID__VOID_UINT_UINT (GClosure     *closure,
                                 GValue       *return_value,
                                 guint         n_param_values,
                                 const GValue *param_values,
                                 gpointer      invocation_hint,
                                 gpointer      marshal_data);

/* VOID:VOID,UINT,POINTER,POINTER,POINTER (src/terminal/marshal:12) */
extern
void v3270_VOID__VOID_UINT_POINTER_POINTER_POINTER (GClosure     *closure,
                                                    GValue       *return_value,
                                                    guint         n_param_values,
                                                    const GValue *param_values,
                                                    gpointer      invocation_hint,
                                                    gpointer      marshal_data);

/* BOOLEAN:VOID,BOOLEAN,UINT,POINTER (src/terminal/marshal:13) */
extern
void v3270_BOOLEAN__VOID_BOOLEAN_UINT_POINTER (GClosure     *closure,
                                               GValue       *return_value,
                                               guint         n_param_values,
                                               const GValue *param_values,
                                               gpointer      invocation_hint,
                                               gpointer      marshal_data);

/* VOID:VOID,POINTER,UINT (src/terminal/marshal:14) */
extern
void v3270_VOID__VOID_POINTER_UINT (GClosure     *closure,
                                    GValue       *return_value,
                                    guint         n_param_values,
                                    const GValue *param_values,
                                    gpointer      invocation_hint,
                                    gpointer      marshal_data);


G_END_DECLS

#endif /* __V3270_MARSHAL_H__ */
